#
# This source file is part of the Stanford CS342 - Building for Digital Health class
#
# SPDX-FileCopyrightText: 2022 Stanford University
#
# SPDX-License-Identifier: MIT
#

body:
- type: input
  id: suggestion
  attributes:
    label: Suggestion
    description: "How might we make this project better?"
    placeholder: "Adding a CODE_OF_CONDUCT.md file would be a great idea."
  validations:
    required: true
