#
# This source file is part of the Stanford CS342 - Building for Digital Health class
#
# SPDX-FileCopyrightText: 2022 Stanford University
#
# SPDX-License-Identifier: MIT
#

title: "[Technical Question] "
labels: ["Technical Question"]
body:
  - type: markdown
    attributes:
      value: |
        Please use this form to describe your technical challenge.
  - type: dropdown
    attributes:
      label: In what area do you have a technical challenge?
      description: | 
        Please refer to [github.com/StanfordBDHG/discussions](https://github.com/orgs/StanfordBDHG/discussions) for any questions regarding StanfordBDHG-related 
        projects such as HealthKitOnFHIR, ResearchKitOnFHIR, CardinalKit, and more ...
      options:
        - Xcode, Simulator & Previews
        - Swift Package Manager
        - Swift
        - SwiftUI
        - HealthKit
        - Other (non-StanfordBDHG-related) area
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a description of the challenge you encountered.
      placeholder: A clear and concise description of the problem you are having. Please include screenshots or error messages.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: | 
        Please provide a description of how to reproduce the problem you are facing.
        
        If you are facing a problem in your application, please provide a link to a failing UI test or unit test to reproduce the issue.
        If you face a build error or a problem with releasing your application, please link a GitHub Action run reproducing the error outside of your development.
      placeholder: | 
        What steps did you follow to get the problem?
        Provide links and steps on how to reproduce the problem.
    validations:
      required: true
  - type: textarea
    id: expectedbehavior
    attributes:
      label: Expected behavior
      description: Please provide a clear and concise description of what you expected to happen.
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: additionalcontext
    attributes:
      label: Additional context
      description:  |
        Please provide any additional context that might be relevant to your setup problem.
      placeholder: Any additional context that might be relevant to your problem.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this course's Code of Conduct and Contributing Guidelines
          required: true
