#
# This source file is part of the Stanford CS342 - Building for Digital Health class
# It is a copy of the xcodebuild-or-fastlane.yml GitHub Action workflow as copied from the Stanford Biodesign Digital Health organization.
#
# SPDX-FileCopyrightText: 2022 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releasetag:
    name: Tag Release
    uses: StanfordBDHG/.github/.github/workflows/action-release-tag.yml@v2
    secrets:
      access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      user: PaulsAutomationBot
