#
# This source file is part of the Stanford CS342 - Building for Digital Health class
#
# SPDX-FileCopyrightText: 2022 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: REUSE Compliance Check

on:
  pull_request:

jobs:
  reuse:
    name: REUSE Compliance Check
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
